-- Dar todos los privilegios al usuario
ALTER USER "LTIdbUser" WITH SUPERUSER;
GRANT ALL PRIVILEGES ON DATABASE "LTIdb" TO "LTIdbUser";
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO "LTIdbUser";
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO "LTIdbUser"; 